model: "FasterSpeech"
sample_rate: &sample_rate 24000
n_mels: &n_mels 64
#num_mels: &num_mels 80
labels: [
  # Space
    ' ',
  # string.ascii_lowercase
    'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm',
    'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z',
  # Punctuation
    "'",
]
#labels: [
#  # Space
#    ' ',
#  # string.ascii_letters
#    'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M',
#    'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z',
#    'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm',
#    'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z',
#  # Punctuation
#    ',', '.', '!', '?', ';', ':', '-', '/',
#    '"', "'", '(', ')', '[', ']', '{', '}',
#]

FasterSpeechDataLayer_train:
    sample_rate: *sample_rate
    max_duration: 20.0  # ~= -30h. This wasn't applied for inferred durations.
    normalize_transcripts: true
    trim_silence: true
    drop_last: true
    shuffle: true

FasterSpeechDataLayer_eval:
    sample_rate: *sample_rate
    normalize_transcripts: true
    trim_silence: true
    drop_last: false
    shuffle: false

AudioToMelSpectrogramPreprocessor:
    window_size: 0.02
    window_stride: 0.01
    window: "hann"
    normalize: "per_feature"
    n_fft: 512
    features: *n_mels
    dither: 0.00001
    pad_to: 16
    sample_rate: *sample_rate
    stft_conv: true
#AudioToMelSpectrogramPreprocessor:
#    dither: 0.0
#    features: *num_mels
#    frame_splicing: 1
#    highfreq: 8000
#    log: true
#    log_zero_guard_type: clamp
#    log_zero_guard_value: 1e-05
#    lowfreq: 0
#    mag_power: 1.0
#    n_fft: 1024
#    n_window_size: 1024
#    n_window_stride: 256
#    normalize: null
#    pad_to: 16
#    pad_value: -11.52
#    preemph: null
#    sample_rate: *sample_rate
#    stft_conv: true
#    window: hann
#    window_size: null
#    window_stride: null

# QuartzNet15x5 without 2x First Stride and Jasper's kernel sizes
JasperEncoder:
    activation: "relu"
    conv_mask: true

    # (Number of Layers) x (Number of Filters) x (Kernel Size)
    jasper:
        # First Layers
        -   filters: 256
            repeat: 1  # First repeat is 1.
            kernel: [11]  # Was 33 in Original QuartzNet15x5 (here and further).
            stride: [1]  # Was 2 in Original QuartzNet15x5.
            dilation: [1]
            dropout: 0.0
            residual: false  # Non-Residual
            separable: true

        # 3 x 256 x 13
        -   filters: 256
            repeat: 5
            kernel: [13]
            stride: [1]
            dilation: [1]
            dropout: 0.0
            residual: true
            separable: true

        -   filters: 256
            repeat: 5
            kernel: [13]
            stride: [1]
            dilation: [1]
            dropout: 0.0
            residual: true
            separable: true

        -   filters: 256
            repeat: 5
            kernel: [13]
            stride: [1]
            dilation: [1]
            dropout: 0.0
            residual: true
            separable: true

        # 3 x 512 x 21
        -   filters: 512
            repeat: 5
            kernel: [21]
            stride: [1]
            dilation: [1]
            dropout: 0.0
            residual: true
            separable: true

        -   filters: 512
            repeat: 5
            kernel: [21]
            stride: [1]
            dilation: [1]
            dropout: 0.0
            residual: true
            separable: true

        -   filters: 512
            repeat: 5
            kernel: [21]
            stride: [1]
            dilation: [1]
            dropout: 0.0
            residual: true
            separable: true

        # 3 x 512 x 25
        -   filters: 512
            repeat: 5
            kernel: [25]
            stride: [1]
            dilation: [1]
            dropout: 0.0
            residual: true
            separable: true

        -   filters: 512
            repeat: 5
            kernel: [25]
            stride: [1]
            dilation: [1]
            dropout: 0.0
            residual: true
            separable: true

        -   filters: 512
            repeat: 5
            kernel: [25]
            stride: [1]
            dilation: [1]
            dropout: 0.0
            residual: true
            separable: true

        # 1 x 512 x 29
        -   filters: 512
            repeat: 1
            kernel: [29]
            stride: [1]
            dilation: [2]
            dropout: 0.0
            residual: false  # Non-Residual
            separable: true

        # Last Layer
        -   filters: 1024
            repeat: 1
            kernel: [1]
            stride: [1]
            dilation: [1]
            dropout: 0.0
            residual: false  # Non-Residual
